[package]
name = "cxxreproduce"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
reqwest = { version = "0.11.13", features = ["blocking"] }

[build-dependencies]
cxx-build = "1.0"
